// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type CodeRequest struct {
	Phone   string `json:"phone"`   // 正确
	Country string `json:"country"` // 正确
}

type CodeResPonse struct {
}