// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"ucenter-api/internal/svc"
)

func RegisterHandlers(server *Routers, serverCtx *svc.ServiceContext) {
	register := NewRegisterHandler(serverCtx)
	registerGroup := server.Group()
	registerGroup.Post("/uc/register/phone", register.Register)
	registerGroup.Post("/uc/mobile/code", register.SendCode)
	loginGroup := server.Group()
	login := NewLoginHandler(serverCtx)
	loginGroup.Post("/uc/login", login.Login)
}
