// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"ucenter-api/internal/svc"
)

func RegisterHandlers(server *Routers, serverCtx *svc.ServiceContext) {
	register := NewRegisterHandler(serverCtx)
	registerRouter := server.Group()
	registerRouter.Get("/uc/register/phone", register.Register)

}
