// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: login.proto

package uclient

import (
	"context"
	"grpc-common/ucenter/types/login"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	loginRegReq = login.LoginReq
	loginRegRes = login.LoginRes

	Login interface {
		Login(ctx context.Context, in *loginRegReq, opts ...grpc.CallOption) (*loginRegRes, error)
	}

	defaultLogin struct {
		cli zrpc.Client
	}
)

func NewLogin(cli zrpc.Client) Login {
	return &defaultLogin{
		cli: cli,
	}
}

func (m *defaultLogin) Login(ctx context.Context, in *loginRegReq, opts ...grpc.CallOption) (*loginRegRes, error) {
	client := login.NewLoginClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}
